# Generated by Django 4.1 on 2022-11-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand_name', models.CharField(blank=True, db_column='brand_name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('slug', models.CharField(blank=True, db_column='slug', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=50)),
            ],
            options={
                'db_table': 'brands',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('slug', models.CharField(blank=True, db_column='slug', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_column='status', default='Active', max_length=50)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('slug', models.CharField(blank=True, db_column='slug', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_column='status', default='Active', max_length=50)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('slug', models.CharField(blank=True, db_column='slug', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_column='status', default='active', max_length=50)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
            options={
                'db_table': 'sub_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, db_column='barcode', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='description', max_length=500, null=True)),
                ('weight', models.DecimalField(db_column='weight', decimal_places=5, default=0.0, max_digits=20)),
                ('height', models.DecimalField(db_column='height', decimal_places=5, default=0.0, max_digits=20)),
                ('width', models.DecimalField(db_column='width', decimal_places=5, default=0.0, max_digits=20)),
                ('length', models.DecimalField(db_column='length', decimal_places=5, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_column='status', default='Active', max_length=50)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brands')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.departments')),
                ('sub_category', models.ForeignKey(blank=True, db_column='sub_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategories')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.departments'),
        ),
    ]
