# Generated by Django 4.2.3 on 2023-07-11 19:33

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('career_summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skype', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('codepen', models.URLField(blank=True, null=True)),
                ('hackerrank', models.URLField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('image', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_currently_working', models.BooleanField(default=False)),
                ('roles', models.TextField(blank=True, max_length=1000, null=True)),
                ('achievements', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.candyprofile')),
                ('technologies', models.ManyToManyField(blank=True, to='resume.topic')),
            ],
            options={
                'ordering': ('from_date',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_type', models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('devops', 'DevOps'), ('other', 'Other')], default='backend', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=100)),
                ('enroll_year', models.DateField(blank=True, null=True)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.candyprofile')),
            ],
        ),
    ]
